### ISSUE TITLE
Server list does not populate due to gameinfo having a different game name

### ISSUE THREAD

**Issue by greatguys1** [GeeTwentyFive/GHSI#1]
gameinfo.txt was changed to have the game name as "HIDDEN: SOURCE - Enhanced Edition". This makes the server browser think this is a different game than the og release. Changing the "game" field back to "Hidden : Source Beta 4b" fixes this issue.

**Comment by GeeTwentyFive** [comment]
Seems to be working for me...?
Are you referring to getting info for other servers?
...or having the listen server populate the Steam master server list?
Do you have an official source for this information or is this a product of speculation and/or experimentation?

**Comment by greatguys1** [comment]
> Seems to be working for me...? Are you referring to getting info for other servers? ...or having the listen server populate the Steam master server list? Do you have an official source for this information or is this a product of speculation and/or experimentation?

Through my own experimentation. However, NOW when I try it, the server list populates. So, sorry for the bad info.
