### ISSUE TITLE
Needed to turn off "read only" mode on appmanifest_215.acf file to get this on Steam

### ISSUE THREAD

**Issue by GregariousJB** [GeeTwentyFive/GHSI#2]
This might be a rare issue or something that happened with Steam recently, I have no idea: After installing the game using the GHSI.exe, then double-clicking the game in Steam to run it, I was met with an error message about "appmanifest_215.acf" being unable to be accessed. I checked its properties and noted that the file was read-only, so I unchecked that attribute and went back to double-clicking the game in Steam. Then, it installed Source SDK fine. 

Just posting this in the off chance that this isn't a rare issue and might need to be amended in the installer or just mentioned in the installation directions. It may help some future users wanting to install this. Or this could just be a one-in-a-million thing that only happened to me. I've been carrying around my /Steam folder for many years through several Windows reformats (on a different drive) so that could be why.

Thanks 👍

**Comment by sonium-labs** [comment]
Me and my homies are trying to play Hidden, and this saved our bacon. Thanks so much for writing it up!

**Comment by jacketattack** [comment]
My friends and I all consistently ran into this issue as well. Thank you for sharing the fix!

To add some detail on fix:
- The mentioned file for us was location at `{pathToYourRootSteamDirectory}/steamapps/appmanifest_215.acf`
  - By default, we see `{pathToYourSteamDirectory}` at `C:/Program Files (x86)/Steam`
- As originally posted, right click on the `appmanifest_215.acf` file
- Uncheck the `Read-only` checkbox near bottom of the 'General' tab in section labeled 'Attributes'
  
![image](https://github.com/user-attachments/assets/8917d418-31e5-4f31-8744-9d4788d7d378)

- Hit 'Ok'
- Game was able to be successfully launched

**Comment by GeeTwentyFive** [comment]
Fixed in V6
